name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up node
      uses: actions/setup-node@v2.4.0
    - name: build
      run: npm run build
